In [99]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [121]:
df = pd.read_csv('data/Mouse_metadata.csv')
df.set_index('Mouse ID', inplace=True)

In [122]:
s = set(df.index.values)

In [123]:
d = pd.DataFrame( )
d['M_ID'] = list(s) 
d['M_VAL'] = np.random.randint(low=1, high=100, size=len(s) )
d.sort_values('M_ID', inplace=True)
d.set_index('M_ID', inplace=True)


d['M_VAL'].values.reshape(-1,1)

array([[ 4],
       [73],
       [35],
       [99],
       [65],
       [22],
       [40],
       [27],
       [ 6],
       [31],
       [13],
       [43],
       [28],
       [ 8],
       [33],
       [89],
       [84],
       [40],
       [22],
       [47],
       [49],
       [53],
       [45],
       [95],
       [97],
       [25],
       [12],
       [75],
       [71],
       [15],
       [66],
       [30],
       [56],
       [65],
       [46],
       [ 7],
       [ 2],
       [57],
       [34],
       [95],
       [69],
       [25],
       [16],
       [68],
       [16],
       [18],
       [52],
       [49],
       [18],
       [77],
       [81],
       [81],
       [92],
       [66],
       [58],
       [46],
       [20],
       [56],
       [ 4],
       [27],
       [93],
       [ 2],
       [56],
       [32],
       [49],
       [59],
       [52],
       [ 8],
       [31],
       [16],
       [74],
       [ 4],
       [47],
       [92],
       [76],
       [95],
       [58],
       [95],
       [45],
       [81],
       [65],
       [39],
       [79],
       [98],
       [76],
       [42],
       [50],
       [14],
       [88],
       [92],
       [49],
       [48],
       [73],
       [65],
       [56],
       [94],
       [86],
       [34],
       [62],
       [74],
       [41],
       [ 3],
       [ 8],
       [83],
       [36],
       [89],
       [46],
       [18],
       [94],
       [13],
       [34],
       [29],
       [17],
       [24],
       [45],
       [38],
       [18],
       [17],
       [ 7],
       [69],
       [30],
       [ 8],
       [53],
       [31],
       [84],
       [51],
       [58],
       [98],
       [ 6],
       [14],
       [35],
       [29],
       [ 4],
       [98],
       [93],
       [ 7],
       [95],
       [97],
       [50],
       [79],
       [35],
       [56],
       [78],
       [47],
       [47],
       [57],
       [32],
       [22],
       [ 3],
       [39],
       [64],
       [ 6],
       [51],
       [ 3],
       [79],
       [13],
       [ 4],
       [87],
       [53],
       [65],
       [19],
       [10],
       [68],
       [54],
       [91],
       [ 9],
       [41],
       [ 2],
       [52],
       [10],
       [45],
       [51],
       [18],
       [72],
       [30],
       [42],
       [20],
       [76],
       [76],
       [11],
       [51],
       [22],
       [75],
       [29],
       [34],
       [32],
       [70],
       [28],
       [72],
       [60],
       [98],
       [16],
       [99],
       [46],
       [34],
       [54],
       [60],
       [78],
       [ 2],
       [ 9],
       [58],
       [75],
       [98],
       [66],
       [53],
       [62],
       [22],
       [33],
       [59],
       [52],
       [48],
       [90],
       [47],
       [10],
       [34],
       [97],
       [13],
       [41],
       [ 4],
       [ 2],
       [72],
       [45],
       [17],
       [76],
       [20],
       [15],
       [87],
       [27],
       [96],
       [94],
       [82],
       [69],
       [53],
       [ 5],
       [75],
       [94],
       [94],
       [46],
       [70],
       [30],
       [ 3],
       [11],
       [51],
       [55],
       [23],
       [76],
       [90],
       [34],
       [40]])

In [124]:
d.loc['a203']

M_VAL    4
Name: a203, dtype: int32

In [131]:
sr = pd.read_csv('data/Study_results.csv')
mm = pd.read_csv('data/Mouse_metadata.csv')

In [135]:
df = pd.merge(sr, mm, on='Mouse ID', how='left'  )
df.drop_duplicates(subset =['Mouse ID', 'Timepoint'], keep = False, inplace = True)
df.head(2)

,Mouse ID,Timepoint,Tumor Volume (mm3),Metastatic Sites,Drug Regimen,Sex,Age_months,Weight (g)
0,b128,0,45.0,0,Capomulin,Female,9,22
1,f932,0,45.0,0,Ketapril,Male,15,29

In [136]:
g = df.groupby('Drug Regimen')['Tumor Volume (mm3)', 'Timepoint' ]
g.describe()

<ipython-input-136-09a98ead79de>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  g = df.groupby('Drug Regimen')['Tumor Volume (mm3)', 'Timepoint' ]

             Tumor Volume (mm3)                                             \
                          count       mean       std        min        25%
Drug Regimen
Capomulin                 230.0  40.675741  4.994774  23.343598  37.685933
Ceftamin                  178.0  52.591172  6.268188  45.000000  47.208427
Infubinol                 178.0  52.884795  6.567243  36.321346  47.312353
Ketapril                  188.0  55.235638  8.279709  45.000000  48.232987
Naftisol                  186.0  54.331565  8.134708  45.000000  47.285874
Placebo                   181.0  54.033581  7.821003  45.000000  47.459053
Propriva                  151.0  52.458254  6.637293  45.000000  47.011050
Ramicane                  228.0  40.216745  4.846308  22.050126  36.674635
Stelasyn                  181.0  54.233149  7.710419  45.000000  48.047139
Zoniferol                 182.0  53.236507  6.966589  45.000000  47.337876

                                              Timepoint                        \
                    50%        75%        max     count       mean        std
Drug Regimen
Capomulin     41.557809  45.000000  48.158209     230.0  21.565217  14.384994
Ceftamin      51.776157  56.801438  68.923185     178.0  19.747191  14.283969
Infubinol     51.820584  57.314444  72.226731     178.0  18.174157  13.473473
Ketapril      53.698743  60.870951  78.567014     188.0  19.707447  14.029935
Naftisol      52.509285  59.963034  76.668817     186.0  19.623656  14.184814
Placebo       52.288934  59.916934  73.212939     181.0  18.674033  13.890798
Propriva      50.854632  56.528101  72.455421     151.0  17.317881  13.672050
Ramicane      40.673236  45.000000  47.622816     228.0  21.425439  14.275720
Stelasyn      52.431737  58.719297  75.123690     181.0  19.226519  13.842710
Zoniferol     51.818479  57.954259  73.324432     182.0  19.368132  14.384679


              min   25%   50%   75%   max
Drug Regimen
Capomulin     0.0  10.0  20.0  35.0  45.0
Ceftamin      0.0   5.0  20.0  30.0  45.0
Infubinol     0.0   5.0  15.0  30.0  45.0
Ketapril      0.0   5.0  20.0  30.0  45.0
Naftisol      0.0   5.0  20.0  30.0  45.0
Placebo       0.0   5.0  15.0  30.0  45.0
Propriva      0.0   5.0  15.0  30.0  45.0
Ramicane      0.0  10.0  20.0  35.0  45.0
Stelasyn      0.0   5.0  20.0  30.0  45.0
Zoniferol     0.0   5.0  15.0  30.0  45.0