In [4]:
import re, subprocess, pyodbc 
import numpy as np # linear algebra 
from sqlalchemy import func, create_engine
from config import mongoConn, connstr  
import pandas as pd 
from os import walk

In [2]:
engine = create_engine(connstr)

In [92]:
dff = pd.DataFrame() 
for (dirpath, dirnames, filenames) in walk(r'D:\dev\CyberScope\CyberScopeBranch\CSwebdev\code\CyberScope.Tests\Selenium\TestData\\'): 
    for f in filenames:
        df = pd.read_csv(f'{dirpath}{f}', index_col=False)  
        dff = pd.concat( [dff , df] )  
    break 
dff

,SectionText,MetricXPath,ErrorAttemptExpression,ExpectedError
0,S1C,"//span[contains(@id, '_tbServiceOffering_wrapp...",^$,Cloud Service
1,S1C,"//span[contains(@id, '_tbService_wrapper')]/input",^$,Service
2,S2,"//*[contains(@class, 'qid_2_1')]",(1.1.1 + 1.1.2) + 1,2.1 should not exceed
3,S2,"//*[contains(@class, 'qid_2_2')]",(1.1.1 + 1.1.2) + 1,2.2 should not exceed
4,S2,"//*[contains(@class, 'qid_2_3')]",(1.1.1 + 1.1.2) + 1,2.3 should not exceed
5,S2,"//*[contains(@class, 'qid_2_4')]",((1.1.1 + 1.1.2) - 2.3) + 1,2.4 should not exceed
6,S2,"//*[contains(@class, 'qid_2_5')]",((1.1.1 + 1.1.2) - (2.3 + 2.4)) + 1,2.5 should not exceed
7,S2,"//*[contains(@class, 'qid_2_6')]",(1.1.1 + 1.1.2) + 1,2.6 should not exceed
8,S2,"//*[contains(@class, 'qid_2_6_1')]",2.6 + 1,2.6.1 should not exceed
9,S2,"//*[contains(@class, 'qid_2_7')]",2.6 + 1,2.7 should not exceed
10,S2,"//*[contains(@class, 'qid_2_8')]",2.6 + 1,2.8 should not exceed
11,S2,"//*[contains(@class, 'qid_2_9')]",2.6 + 1,2.9 should not exceed
12,S2,"//*[contains(@class, 'qid_2_10')]",(1.1.1 + 1.1.2) + 1,2.10 should not exceed
13,S2,"//*[contains(@class, 'qid_2_10_1')]",( 2.10 ) + 1,2.10.1 should not exceed
14,S2,"//*[contains(@class, 'qid_2_10_2')]",( 2.10 - 2.10.1 ) + 1,2.10.2 should not exceed
15,S2,"//*[contains(@class, 'qid_2_10_3')]",( 2.10 - ( 2.10.1 - 2.10.2 )) + 1,2.10.3 should not exceed
16,S2,"//*[contains(@class, 'qid_2_10_4')]",( 2.10 ) + 1,2.10.4 should not exceed
17,S2,"//*[contains(@class, 'qid_2_10_5')]",( 2.10 ) + 1,2.10.5 should not exceed
18,S4,"//*[contains(@class, 'qid_4_1_1_a')]",( 4.1 ) + 1,4.1.1.a should not exceed
19,S4,"//*[contains(@class, 'qid_4_1_1_b')]",( 4.1 ) + 1,4.1.1.b should not exceed
20,S4,"//*[contains(@class, 'qid_4_1_1_c')]",( 4.1 ) + 1,4.1.1.c should not exceed
21,S4,"//*[contains(@class, 'qid_4_1_2_a')]",( 4.1 ) + 1,4.1.2.a should not exceed
22,S4,"//*[contains(@class, 'qid_4_1_2_b')]",( 4.1 ) + 1,4.1.2.b should not exceed
23,S4,"//*[contains(@class, 'qid_4_1_2_c')]",( 4.1 ) + 1,4.1.2.c should not exceed
24,S4,"//*[contains(@class, 'qid_4_1_3_a')]",( 4.1 ) + 1,4.1.3.a should not exceed
25,S4,"//*[contains(@class, 'qid_4_1_3_b')]",( 4.1 ) + 1,4.1.3.b should not exceed
26,S4,"//*[contains(@class, 'qid_4_1_3_c')]",( 4.1 ) + 1,4.1.3.c should not exceed
27,S4,"//*[contains(@class, 'qid_4_1_4_a')]",( 4.1 ) + 1,4.1.4.a should not exceed
28,S4,"//*[contains(@class, 'qid_4_1_4_b')]",( 4.1 ) + 1,4.1.4.b should not exceed
29,S4,"//*[contains(@class, 'qid_4_1_4_c')]",( 4.1 ) + 1,4.1.4.c should not exceed
30,S4,"//*[contains(@class, 'qid_4_1_5_a')]",( 4.1 ) + 1,4.1.5.a should not exceed
31,S4,"//*[contains(@class, 'qid_4_1_5_b')]",( 4.1 ) + 1,4.1.5.b should not exceed
32,S4,"//*[contains(@class, 'qid_4_1_5_c')]",( 4.1 ) + 1,4.1.5.c should not exceed
33,S4,"//*[contains(@class, 'qid_4_1_6_a')]",( 4.1 ) + 1,4.1.6.a should not exceed
34,S4,"//*[contains(@class, 'qid_4_1_6_b')]",( 4.1 ) + 1,4.1.6.b should not exceed
35,S4,"//*[contains(@class, 'qid_4_1_6_c')]",( 4.1 ) + 1,4.1.6.c should not exceed
36,S4,"//*[contains(@class, 'qid_4_1_7_a')]",( 4.1 ) + 1,4.1.7.a should not exceed
37,S4,"//*[contains(@class, 'qid_4_1_7_b')]",( 4.1 ) + 1,4.1.7.b should not exceed
38,S4,"//*[contains(@class, 'qid_4_1_7_c')]",( 4.1 ) + 1,4.1.7.c should not exceed
39,7A,"//tr[contains(@id, '__0')]//*[contains(@id, 'S...",(1.1.1 + 1.1.2) + 1,exceed
40,7A,"//tr[contains(@id, '__1')]//*[contains(@id, 'S...",(1.1.1 + 1.1.2) + 1,exceed
0,S2,"//*[contains(@class, 'qid_2_1')]",(1.1.1 + 1.1.2) + 1,2.1 should not exceed
1,S2,"//*[contains(@class, 'qid_2_2')]",(1.1.1 + 1.1.2) + 1,2.2 should not exceed
0,Section 7:,"//*[contains(@class, 'BGPPeerIP')]",09.123.123.123,
1,Section 7:,"//*[contains(@class, 'BGPPeerIP')]",2001:cdba:0000:0000:0000:0000:3257:9652,NaN
2,Section 7:,"//*[contains(@class, 'BGPPeerIP')]",2001:cdba:0000:0000:0000:0000:3257:9652/12,BGP
3,Section 7:,"//*[contains(@class, 'BGPPeerIP')]",123.123.123/12,BGP
4,Section 7:,"//*[contains(@class, 'BGPPeerIP')]",256.2.3.4,BGP
5,Section 7:,"//*[contains(@class, 'BGPPeerIP')]",^$,BGP

In [91]:
p='D:\dev\CyberScope\CyberScopeBranch\CSwebdev\code\CyberScope.Tests\Selenium\TestData\\'
dff.to_csv(f'{p}_Validations.csv', index=False)

df = pd.read_excel(r'C:\Users\Tim\Downloads\BOD2201_2021_2_VALID.xlsx').fillna('')
df['Unremediated Count Justification'] = 'Justification' 
df.columns = [c.replace(' ' , ' ') for c in df.columns] 
df.loc[df.CVE=='CVE-2011-3544', 'Unremediated Count Justification'] = ''
df.loc[df.CVE=='CVE-2011-3544', 'Total Unremediated Assets'] = '9999999'
df.columns
df.to_excel(r'C:\Users\Tim\Downloads\BOD2201_2021_2_INVALID.xlsx', index=False) 
df